server:
  port: 8086

spring:
  application:
    name: reporting-service
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate # Read-only, so validate schema exists
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

spring.datasource:
  url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:-5432}/${POSTGRES_DB}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  driver-class-name: org.postgresql.Driver
